services:
  testnanaloga1.api:
    image: ${DOCKER_REGISTRY-}testnanaloga1api
    container_name: zahtevek.api
    build:
      context: .
      dockerfile: TestnaNaloga1/Dockerfile
    ports:
      - "8080:5000"
      - "8081:5001"
